### ISSUE TITLE
RFE: Pacakges for different Python version

### ISSUE THREAD

**Issue by hroncok** [befeleme/pyp2spec#16]
This is a very low-priority RFE.

I'd like to be able to create a package for e.g. Python 3.12 when the "main" Python is 3.9. This is relevant namely on EL9.

Such packages will differ in a way:

 - `%{python3_pkgversion}` will be set globally to given 3.X (and `%{__python3}` will be set globally to `/usr/bin/python3.X` until [this is merged](https://src.fedoraproject.org/rpms/python-rpm-macros/pull-request/127) to c9s)
 - the name will be `python%{python3_pkgversion}-xxx`
 - there will be no `python3-xxx` subpacakge, the content will be delivered via the main package
 - any `python3-xxx` (build)requires need to be versioned, e.g. `python%{python3_pkgversion}-devel`

**Comment by MrMEEE** [comment]
Is someone actively working on this? I could REALLY use the feature.. If nobody is working on it, I might give it a shot..

**Comment by MrMEEE** [comment]
@befeleme PR commited, please tell me if there is anything missing..

**Comment by befeleme** [comment]
Thank you! Can you share what your use case is/ for which OS you'd like to generate specfiles? The reason I'm asking it because your PR generates slightly different output than what's requested by @hroncok. So I'd like to know more before addressing that. I'll do the review in the upcoming days.

**Comment by befeleme** [comment]
Please take a look at #46 and let me know if this generally covers your needs.
