### ISSUE TITLE
Relicensing the spec template to MIT No Attribution (SPDX: MIT-0)

### ISSUE THREAD

**Issue by hroncok** [befeleme/pyp2spec#25]
Considering Fedora is [going to prohibit CC0 for code](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/RRYM3CLYJYW64VSQIXY6IF3TCDZGS6LM/) at least for new packages, I'd like to relicense the template to [MIT No Attribution](https://opensource.org/licenses/MIT-0) (SPDX: *MIT-0*) before it has too many contributors.

Looking at https://github.com/befeleme/pyp2spec/blob/main/pyp2spec/template.spec it seems it is created only by @befeleme and @hroncok.

WDYT?

**Comment by befeleme** [comment]
Thank you for spotting the issue and bringing it here, I agree it's a good idea to relicense the template. I'll prepare the change soon.

**Comment by hroncok** [comment]
For the record, I also agree with relicensing my contributions to the template that way.
