### ISSUE TITLE
License compliance

### ISSUE THREAD

**Issue by pkking** [befeleme/pyp2spec#29]
When im building a pypi package in copr, i met this:
```
...
License 'Freely Distributable' is or may not be allowed in Fedora, quitting
stderr: 

Unable to generate spec for `cherrypy'
```
https://download.copr.fedorainfracloud.org/results/lcrpkking/waaagh/srpm-builds/05088358/builder-live.log.gz

Im not sure the `Freely Distributable` is forbidden by fedora or its just a misjudge

**Comment by hroncok** [comment]
I am afraid Freely Distributable is not a free software license. I wonder why cherrypy lists that instead of just listing the actual BSD license.

**Comment by befeleme** [comment]
@pkking, the question of licensing is rather an unpleasant one. If an upstream project defines more classifiers, one which is free (BSD), and one that isn't (Freely Distributable) we can't just choose one of them and declare that the project is "good for Fedora". 
In this case, cherrypy should stop using the `'License :: Freely Distributable'` classifier.

**Comment by befeleme** [comment]
What you can do about it?
- ask upstream to delete the `'License :: Freely Distributable'` - the best option, will stop causing problems in the future for the others
- (optionally) you can review the actual license of the project, which is BSD-3-Clause. You can build the package in Copr with a `custom` build method. As a script invoke `pyp2spec cherrypy --top-level --license BSD-3-Clause` and define `pyp2spec` as a build dependency. This will skip the license compliance phase and set the value you chose. Be mindful that Copr only allows to build packages with free licenses, same as Fedora (https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr)

**Comment by befeleme** [comment]
There's another bad news. Fedora is migrating to SPDX standard which is more strict, and it's impossible to tell automatically whether `BSD License` is BSD-2-Clause or BSD-3-Clause. Soon this will start creating problems too. I really hope that Python projects switch to the standard too, so that we don't have to translate the classifiers anymore. But that's just future... In the meantime, the tips from the previous answer are still valid.

**Comment by pkking** [comment]
Will try to ping the upstream, thanks.

**Comment by webknjaz** [comment]
FTR upstream is fine with dropping that trove classifier: https://github.com/cherrypy/cherrypy/issues/1981#issuecomment-2983872973.
