### ISSUE TITLE
Distribute the tool as Python package

### ISSUE THREAD

**Issue by befeleme** [befeleme/pyp2spec#3]

**Comment by PatrikKopkan** [comment]
Hi, I would like to help with this. Is there any specific requirement? Is setuptools satisfying?

**Comment by encukou** [comment]
setuptools is great! Preferably with [setup.cfg](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html) and [pyproject.toml](https://setuptools.pypa.io/en/latest/build_meta.html#how-to-use-it).
