### ISSUE TITLE
Fatal exception occurred: sdist not found.

### ISSUE THREAD

**Issue by brianjmurrell** [befeleme/pyp2spec#43]
Sorry if this is obvious but I'm not much of a Python module packager:

```
$ pyp2spec mac-vendor-lookup -l Apache-2.0
Generating configuration file
Assuming 'mac-vendor-lookup' is a package name
Querying PyPI for package 'mac-vendor-lookup'
Assuming --description=This is package 'mac-vendor-lookup' generated automatically by pyp2spec.
Assuming --summary=Find the vendor for a given MAC address
Assuming PyPI --version=0.1.12
Fatal exception occurred: sdist not found.
```

Is this just a completely broken Python module?  I'd assume `pip` is able to install it at least.

**Comment by hroncok** [comment]
https://pypi.org/project/mac-vendor-lookup/0.1.12/#files only lists a .whl file. This is a perfectly valid file for pip to install, however, it is not a "source tarball" that is required to build an RPM package. You could use a tagged release tarball from [upstream github](https://github.com/bauerj/mac_vendor_lookup) to build an RPM, but I am not sure if you can use `pyp2spec` directly or not. Note that version 0.1.12 appears missing from https://github.com/bauerj/mac_vendor_lookup/tags -- so you will probably need to ask upstream to tag it. While talking to them, you may as well ask them to release sdist on pypi.
