### ISSUE TITLE
Warn if the detected license isn't a valid SPDX, don't error

### ISSUE THREAD

**Issue by befeleme** [befeleme/pyp2spec#47]
When Copr adds a license-validate check to its repositories, pyp2spec doesn't have to be so strict in the automatic mode anymore: https://github.com/fedora-copr/copr/issues/3290

Only warning should be sufficient for the human user, whom we expect to review the generated specfile anyway.

**Comment by trixirt** [comment]
The fedora-review will catch these problems so it is not necessary to error out.

**Comment by brianjmurrell** [comment]
Clearly something needs to happen here.  Waiting for upstreams to fix metadata problems in their packages before COPR will successfully build them is just unworkable.  I have been waiting literally weeks (if not months) for an upstream to simply fix their SPDX licence and it's still not done, making this package unbuildable in COPR.

**Comment by hroncok** [comment]
You don't need to use automatic pyp2spec conversion to build the package in copr.

**Comment by brianjmurrell** [comment]
I do if I want to use _Anitya autorebuild_ on it and `pyp2rpm` [fails to build the package](https://copr.fedorainfracloud.org/coprs/brianjmurrell/PyPI/build/7630438/).

Apart from the SPDX license barf, `pyp2spec` builds the package fine.
